title: I-Da Chiang
description: A PhD candidate in astrophysics <br/> at CASS, UCSD <br/> E-mail&#58; idchiang at ucsd.edu
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, astronomy, ISM, dust, 江宜達
show_downloads: false
theme: jekyll-theme-minimal
