title: I-Da Chiang
description: Pronounciation notes&#58; 	&#91;ee-da jiang&#93; <br/> <a href="https://www.name-coach.com/i-da-chiang" target="_blank">How to pronounce my name?</a>
 <br/> <br/> Postdoc Fellow <br/> ASIAA, Taiwan <br/><br/> E-mail&#58; idchiang<code>&#64;</code>asiaa.sinica.edu.tw
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, astronomy, ISM, dust, 江宜達, ASIAA, Taiwan
show_downloads: false
theme: jekyll-theme-minimal
