title: I-Da Chiang
description: PhD student at CASS, UCSD <a href="https://orcid.org/0000-0003-2551-7148" target="orcid.widget" rel="noopener noreferrer" style="vertical-align:top;"><img src="https://orcid.org/sites/default/files/images/orcid_16x16.png" style="width:1em;margin-right:.5em;" alt="ORCID iD icon">orcid.org/0000-0003-2551-7148</a>
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, 江宜達
show_downloads: false
theme: jekyll-theme-minimal
