title: I-Da Chiang
description: PhD candidate at CASS, UCSD <br /> E-mail&#58; idchiang at ucsd.edu
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, radio astronomy, 江宜達
show_downloads: false
theme: jekyll-theme-minimal
