title: I-Da Chiang
description: PhD Candidate <br/> Observational Astrophysics <br/> CASS, UCSD <br/><br/> E-mail&#58; idchiang<code>&#64;</code>ucsd.edu
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, astronomy, ISM, dust, 江宜達
show_downloads: false
theme: jekyll-theme-minimal
