title: I-Da Chiang
description: Pronouns&#58; he/him/his <br/> <br/> Postdoc Fellow <br/> ASIAA, Taiwan <br/><br/> E-mail&#58; idchiang<code>&#64;</code>asiaa.sinica.edu.tw
google_analytics: I-Da Chiang, UCSD, CASS, physics, astrophysics, astronomy, ISM, dust, 江宜達, ASIAA, Taiwan
show_downloads: false
theme: jekyll-theme-minimal
